ProjectS/Models/Blog.cs
namespace Project.Models
{
    public class Blog
    {
        public int Blogid { get; set; }
        public bool? HomeStatus { get; set; }
        public string content { get; set; } = null!;
        public string content2 { get; set; } = null!;
        public DateTime? DateUp { get; set; }
        public string name { get; set; } = null!;
        public bool isCollection { get; set; }
        public virtual List<ImageBlog> ImageBlogs { get; set; } = null!;
        public virtual List<Product> Products { get; set; } = null!;
        public virtual List<Comment> Comment { get; set; }=null!;

    }
}

ProjectS/Areas/Admin/Pages/Role/Update.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Project.Data;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;
using System.Threading.Tasks;

namespace Project.Admin.Role
{
	[Authorize(Roles = "Admin")]

	public class UpdateModel : RolePageModel
    {

        public UpdateModel(RoleManager<IdentityRole> roleManager, ShopContext shopContext) : base(roleManager, shopContext)
        {
        }

        public class InputModel
		{
			[Display(Name = "Tên của role")]
			[Required(ErrorMessage = "Phải nhập {0}")]
			[StringLength(230, MinimumLength = 3, ErrorMessage = "{0} phải dài {2} đến {1} kí tự")]
			public string Name { get; set; }
		}

		[BindProperty]
		public InputModel Input { get; set; }
		public IdentityRole role { get; set; }

		public async Task<IActionResult> OnGet(string roleid)
		{
			if(roleid == null) return NotFound("Không tìm thấy role");

			 role = await _roleManager.FindByIdAsync(roleid);

			if(role != null)
			{
				Input = new InputModel
				{
					Name = role.Name
				};
				return Page();
			}
            return NotFound("Không tìm thấy role");
        }

		public async Task<IActionResult> OnPostAsync(string roleid)
		{
            if (roleid == null) return NotFound("Không tìm thấy role");

             role = await _roleManager.FindByIdAsync(roleid);
            if (roleid == null) return NotFound("Không tìm thấy role");


            if (!ModelState.IsValid)
			{
				return Page();
			}
			role.Name =Input.Name;
			var result=await _roleManager.UpdateAsync(role);



			if (result.Succeeded)
			{

				StatusMessage = $"Bạn vừa sửa role: {Input.Name}";
				return RedirectToPage("./Index");
			}
			else
			{
				result.Errors.ToList().ForEach(error =>
				{
					ModelState.AddModelError(string.Empty, error.Description);
				});
			}

			return Page();
		}
	}
}

ProjectS/Controllers/BlogController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Project.Data;
using Project.Models;
using System.Drawing.Imaging;
using System.Linq;
using System.Reflection.Metadata;
using WebApplication6.Service;

namespace Project.Controllers
{
    public class BlogController : Controller
    {
        private readonly ShopContext _context;
        private readonly ICloudinaryService _cloudinaryService;


        public BlogController(ShopContext context, ICloudinaryService temp)
        {
            _context = context;
            _cloudinaryService = temp;

        }

        public IActionResult Index()
        {
            var blogs = _context.Blogs
            .Include(b => b.ImageBlogs)
            .Where(b => b.ImageBlogs.Any(ib => ib.IsBigImg == true))
            .Select(b => new
            {
                b.name,
                b.Blogid,
                b.HomeStatus,
                b.content,
                b.DateUp,
                FirstImage = b.ImageBlogs.Single(ib => ib.IsBigImg == true).ImageURL
            })
            .ToList();



            return View(blogs);
        }


        public IActionResult BlogDetails(int blogId)
        {
            var check = _context.Blogs.Find(blogId);

            if (check == null)
            {
                return RedirectToAction("Index");
            }
            else
            {
                var blog = _context.Blogs
               .Include(b => b.Products)
               .Include(b => b.ImageBlogs)
               .Include(c => c.Comment)
                .ThenInclude(c => c.User)
               .Include(c => c.Comment)
                .ThenInclude(d => d.Answers)
                .ThenInclude(c => c.User)

               .FirstOrDefault(b => b.Blogid == blogId);
                return View(blog);
            }
        }

        [Authorize(Roles = "Seller, Admin, Marketing")]
        public IActionResult ViewBlog()
        {
            List<Blog> blog = _context.Blogs.ToList();


            return View(blog);
        }

        public IActionResult ChangeStatus(int id)
        {
            var blog = _context.Blogs.FirstOrDefault(b => b.Blogid == id);

            if (blog != null)
            {
                blog.HomeStatus = !blog.HomeStatus;
                _context.SaveChanges();
            }

            return RedirectToAction("ViewBlog");
        }

        public IActionResult Delete(int id)
        {
            var blog = _context.Blogs.FirstOrDefault(b => b.Blogid == id);

            if (blog != null)
            {
                _context.Blogs.Remove(blog);
                _context.SaveChanges();
            }

            return RedirectToAction("ViewBlog");
        }

        public IActionResult ViewDetail(int id)
        {
            Blog blog = _context.Blogs.Include(b => b.ImageBlogs)
                                      .Include(b => b.Products)
                                      .FirstOrDefault(b => b.Blogid == id);

            if (blog == null)
            {
                TempData["checked"] = "";
                return Redirect("/Blog/ViewBlog");
            }

            return View(blog);
        }

        [Authorize(Roles = "Seller, Admin, Marketing")]
        public IActionResult CreateBlog()
        {
            return View();
        }

        [Authorize(Roles = "Seller, Admin, Marketing")]
        [HttpPost]
        public IActionResult CreateBlog(Blog blog)
        {
            _context.Blogs.Add(blog);
            _context.SaveChanges();

            return Redirect($"CreateImage?id={blog.Blogid}");

        }

        public IActionResult CreateImage(int id)
        {

            var blog = _context.Blogs.Include(b => b.ImageBlogs).FirstOrDefault(b => b.Blogid == id);


            return View(blog);
        }

        [HttpPost]
        public IActionResult CreateImage(IFormFile ImageUrl, ImageBlog imageBlog)
        {
            var UrlImage = _cloudinaryService.UploadImage(ImageUrl, "ImageBlog");

            imageBlog.ImageURL = UrlImage;

            _context.ImageBlogs.Add(imageBlog);
            _context.SaveChanges();

            return Redirect($"CreateImage?id={imageBlog.BlogId}");

        }

        public IActionResult Update(int id)
        {
            var blog = _context.Blogs.FirstOrDefault(b => b.Blogid == id);

            if (blog != null)
            {
                return View(blog);
            }
            else
            {
                TempData["checked"] = "";
                return Redirect("/Blog/ViewBlog");
            }
        }

        [HttpPost]
        public IActionResult Update(Blog updatedBlog)
        {
            var blog = _context.Blogs.FirstOrDefault(b => b.Blogid == updatedBlog.Blogid);

            if (blog != null)
            {
                blog.HomeStatus = updatedBlog.HomeStatus;
                blog.content = updatedBlog.content;
                blog.DateUp = updatedBlog.DateUp;
                blog.name = updatedBlog.name;
                blog.isCollection = updatedBlog.isCollection;
                blog.content2 = updatedBlog.content2;

                _context.SaveChanges();
            }

            return Redirect($"UpdateImage?id={updatedBlog.Blogid}");
        }

        public IActionResult UpdateImage(int id)
        {
            List<ImageBlog> img = _context.ImageBlogs
                .Where(image => image.BlogId == id)
                .ToList();
            var blog = _context.Blogs.FirstOrDefault(b => b.Blogid == id);

            if (blog == null)
            {
                TempData["checked"] = "";
                return Redirect("/Blog/ViewBlog");
            }

            return View(img);
        }

        [HttpPost]
        public IActionResult CreateImage2(IFormFile ImageUrl, ImageBlog imageBlog)
        {
            var UrlImage = _cloudinaryService.UploadImage(ImageUrl, "ImageBlog");

            imageBlog.ImageURL = UrlImage;

            _context.ImageBlogs.Add(imageBlog);
            _context.SaveChanges();

            return Redirect($"UpdateImage?id={imageBlog.BlogId}");

        }

        [HttpPost]
        public async Task<IActionResult> UpdateImage(int ImageId, int BlogId, string ImageUrl, bool IsBigImg, DateTime DateUp, [FromForm] IFormFile NewImageUrl, int FormId)
        {
            if (FormId == ImageId)
            {

                var newImageUrl = ImageUrl;

                if (NewImageUrl?.Length > 0)
                {
                    newImageUrl = _cloudinaryService.UploadImage(NewImageUrl, "ImageBlog");
                }

                var image = _context.ImageBlogs.FirstOrDefault(i => i.ImageBlogId == ImageId);

                Console.WriteLine(newImageUrl);

                if (image != null)
                {
                    image.BlogId = BlogId;

                    image.ImageURL = newImageUrl;

                    image.IsBigImg = IsBigImg;
                    image.DateUp = DateUp;

                    _context.ImageBlogs.Update(image);
                    _context.SaveChanges();
                    return RedirectToAction("UpdateImage", new { id = BlogId });
                }
            }

            return RedirectToAction("ViewBlog");
        }

        public IActionResult searchBlogByName(string name)
        {
            List<Blog> blog = null;

            if (name != null)
            {
                blog = _context.Blogs.Where(x => x.name.Contains(name)).ToList();
            }
            else

                blog = _context.Blogs.ToList();

            return View(blog);
        }






    }

}

ProjectS/Views/Blog/CreateBlog.cshtml
@model Blog

@{
    Layout = "~/Views/Shared/_DashLayout.cshtml";
}


<div class="container-fluid dashboard-content ">

    <!-- pageheader  -->

    <div class="row">
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
            <div class="page-header">
                <h2 class="pageheader-title">Quản Lý  </h2>
                <div class="page-breadcrumb">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#" class="breadcrumb-link">Dashboard</a></li>
                            <li class="breadcrumb-item"><a href="#" class="breadcrumb-link">View Blog</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Create blog</li>
                        </ol>
                    </nav>
                </div>
            </div>

        </div>
    </div>

    <main role="main">
        <form action="/Blog/CreateBlog" method="post">
            <div class="container" style="background: white;border-radius:5px">
                <div class="row">
                    <div class="col-md-6">
                        <br />
                        <div class="form-group">
                            <label for="HomeStatus">Home Status</label>
                            <select id="HomeStatus" name="HomeStatus" class="form-control" style="border-radius:5px">
                                <option value="true">Enable</option>
                                <option value="false">Disable</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="DateUp">Date Updated</label>
                            <input type="datetime" id="DateUp" name="DateUp" class="form-control" value="@DateTime.Now.ToString("yyyy-MM-dd")" style="border-radius:5px" required />
                        </div>
                    </div>

                    <div class="col-md-6">
                        <br />
                        <div class="form-group">
                            <label for="Name">Name</label>
                            <input type="text" id="Name" name="Name" class="form-control" style="border-radius:5px" required />
                        </div>

                        <div class="form-check">
                            <br /><br />
                            <input class="form-check-input" type="checkbox" id="IsCollection" name="IsCollection" value="true" />
                            <label class="form-check-label" for="IsCollection">Is Collection</label>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label for="Content">Content</label>
                    <textarea id="Content" name="Content" class="form-control" style="border-radius:5px" required></textarea>
                </div>

                <div class="form-group">
                    <label for="Content2">Second Content</label>
                    <textarea id="Content2" name="Content2" class="form-control" style="border-radius:5px" required></textarea>
                </div>
                <div>
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a href="/Blog/ViewBlog" class="btn btn-secondary">Cancel</a>

                </div><br />
            </div>
        </form>
    </main>
    <!-- end pageheader  -->
</div>

ProjectS/Views/Blog/CreateImage.cshtml
@model Blog

@{
    Layout = "~/Views/Shared/_DashLayout.cshtml";
}

<div class="container-fluid dashboard-content ">

    <!-- pageheader  -->

    <div class="row">
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
            <div class="page-header">
                <h2 class="pageheader-title">Quản Lý  </h2>
                <div class="page-breadcrumb">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#" class="breadcrumb-link">Dashboard</a></li>
                            <li class="breadcrumb-item"><a href="#" class="breadcrumb-link">View Blog</a></li>
                            <li class="breadcrumb-item"><a href="#" class="breadcrumb-link">Create blog</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Create blog image</li>
                        </ol>
                    </nav>
                </div>
            </div>

        </div>
    </div>

    <main role="main">
        <form>
            <h3>Blog Details:</h3>

            <input type="hidden" id="Blogid" name="Blogid" value="@Model.Blogid" />
            <div class="container" style="background: white;border-radius:5px">
                <div class="row">
                    <div class="col-md-6">
                        <br />
                        <div class="form-group">
                            <label for="HomeStatus">Home Status</label>
                            <input type="text" id="HomeStatus" name="HomeStatus" value="@(Model.HomeStatus == true ? "Enable" : "Disable")" readonly class="form-control" />
                        </div>

                        <div class="form-group">
                            <label for="DateUp">Date Up</label>
                            <input type="text" id="Date Up" name="Date Up" value="@Model.DateUp" readonly class="form-control" />
                        </div>
                    </div>
                    <div class="col-md-6">
                        <br />
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" id="name" name="name" value="@Model.name" readonly class="form-control" />
                        </div>

                        <div class="form-group">
                            <label for="isCollection">Is Collection</label>
                            <input type="text" id="isCollection" name="isCollection" value="@Model.isCollection.ToString()" readonly class="form-control" />
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label for="content">Content</label>
                    <textarea id="content" name="content" readonly class="form-control">@Model.content</textarea>
                </div>

                <div class="form-group">
                    <label for="content2">Second Content</label>
                    <textarea id="content2" name="content2" readonly class="form-control">@Model.content2</textarea>
                </div><br />

            </div>
        </form>
        <hr />
        @foreach (var l in Model.ImageBlogs)
        {
            <img src="@l.ImageURL" style="width: 200px; height: 150px">
        }
        <hr />
        <form action="/Blog/CreateImage" method="post" enctype="multipart/form-data">

            <h3>Image Details:</h3>

            <input type="hidden" id="Blogid" name="Blogid" value="@Model.Blogid" class="form-control" />

            <div class="container" style="background: white;border-radius:5px">
                <br />
                <div class="form-group">
                    <label for="ImageUrl">Image URL</label>
                    <input type="file" id="ImageUrl" name="ImageUrl" class="form-control" required />
                </div>

                <div class="form-group">
                    <label for="DateUp">Date Up</label>
                    <input type="datetime" id="DateUp" name="DateUp" class="form-control" value="@DateTime.Now.ToString("yyyy-MM-dd")" required />
                </div>

                <div class="form-check">
                    <input class="form-check-input" type="checkbox" id="IsBigImg" name="IsBigImg" value="true" />
                    <label class="form-check-label" for="IsBigImg">IsBigImg</label>
                </div><br />

                <div>
                    <button type="submit" id="submitButton" class="btn btn-primary">Create Image</button>
                    <a href="/Blog/ViewBlog" class="btn btn-primary">View Blog</a>
                </div><br />
            </div>

        </form>
        <script>
            document.getElementById('ImageUrl').addEventListener('change', function () {
                var fileInput = document.getElementById('ImageUrl');
                var submitButton = document.getElementById('submitButton');

                if (fileInput.files && fileInput.files[0]) {
                    submitButton.disabled = false;
                } else {
                    submitButton.disabled = true;
                }
            });
        </script>
        
      
    </main>
    <!-- end pageheader  -->
</div>

ProjectS/Views/Blog/Index.cshtml
@model IEnumerable<dynamic>

<!-- blogcss -->
<link rel="stylesheet" href="~/blogcss/css/style.css">
<!-- end blogcss -->
<!-- royal_loader -->
<div style="background-color: #ffffff;" class="">
    <div class="boxed no-padding bg-img" style="background-image: url('https://res.cloudinary.com/dtwmfo4fl/image/upload/v1687962616/blog-bg_gjxwsw.jpg');">
        <div class="sub-header depen-on-img d-flex justify-content-center align-items-center" style="width: 70%;">
            <img src="https://res.cloudinary.com/dtwmfo4fl/image/upload/v1687962616/blog-bg_gjxwsw.jpg" class="img-responsive" alt="Image">
            <div class="sub-header-inner center-center">
                <h2>BLOG</h2>
            </div>
        </div>
    </div>


    <!-- /subheader -->

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="blog-list">

                    @foreach (var blog in Model)
                    {
                        <div class="item-post pt--30">
                            <a href="/blog/BlogDetails?blogId=@blog.Blogid">
                                <img src="@blog.FirstImage" class="img-responsive" alt="Image">
                            </a>
                            <div class="desc">
                                <h4><a href="/blog/BlogDetails?blogId=@blog.Blogid">@blog.name </a></h4>
                                <div class="meta">
                                    <span class="meta-date">@blog.DateUp.ToString("MMMM, dd\"th\", yyyy")</span><span class="meta-author"> - by <a href="/blog/BlogDetails?blogId=@blog.Blogid">Crophos</a> </span><span class="meta-cate"> - in <a href="blog.html">Design</a></span>
                                </div>
                                <div class="meta">
                                </div>

                                @if (blog.content.Length > 195)
                                {
                                    <p>@blog.content.Substring(0, 194) ...</p>
                                }
                                else
                                {
                                    <p>@blog.content</p>
                                }

                                <a href="/blog/BlogDetails?blogId=@blog.Blogid" class="ot-btn border-dark">Read More</a>
                            </div>
                        </div>
                        <hr style="background-color: #896868;height:3px">
                    }
                </div>
            </div>
        </div>
    </div>
    <!-- /Bloglist -->
</div>

ProjectS/Views/Blog/ViewBlog.cshtml
@model List<Blog>

@{
    Layout = "~/Views/Shared/_DashLayout.cshtml";
}


<script>
    function check(event) {
        var confirmation = confirm("Are you sure you want to delete?");

        if (!confirmation) {
            event.preventDefault();
            return false;
        } else {
            return true;
        }

    }
</script>

<div class="container-fluid dashboard-content ">

    <!-- pageheader  -->

    <div class="row">
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
            <div class="page-header">
                <h2 class="pageheader-title">Quản Lý  </h2>
                <div class="page-breadcrumb">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#" class="breadcrumb-link">Dashboard</a></li>
                            <li class="breadcrumb-item active" aria-current="page">View blogs</li>
                        </ol>
                    </nav>
                </div>
            </div>

        </div>
    </div>

    <main role="main">
        @if (TempData["checked"] != null)
        {
            <script>
                var mes = "Blog bạn muốn tìm không tồn tại, click Ok để tiếp tục."
                alert(mes);
            </script>
        }
        @if (Model == null)
        {
            <p>No blogs found.</p>
        }
        else
        {
            <div class="card">
                <div class="card-body">
                    <div class="d-lg-flex align-items-center mb-4 gap-3">
                        <div class="position-relative">
                            <input oninput="SearchByname()" type="text" id="searchBlog" class="form-control ps-5 radius-30" placeholder="Blog Name">
                        </div>
                        <div class="ms-auto">
                            <a href="/Blog/CreateBlog" class="btn btn-primary radius-30 mt-2 mt-lg-0" style=" margin-left: 10px; "><i class="bx bxs-plus-square"></i>Add New Blog</a>
                        </div>
                    </div>

                    <div class="table-responsive">
                        <div id="_blogList">
                            @if (Model.Count > 0)
                            {
                                <div class="table-responsive">
                                    <table class="table mb-0">
                                        <thead class="table-light">
                                            <tr>
                                                <th>Blog ID</th>
                                                <th>Name</th>
                                                <th>HomeStatus</th>
                                                <th>Actions</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var blog in Model)
                                            {
                                                <form method="post" asp-controller="Blog" asp-action="">
                                                    <input type="hidden" name="billId" value="@blog.Blogid" />

                                                <tr>
                                                    <td>
                                                        <div class="d-flex align-items-center">

                                                            <div class="ms-2">
                                                                <h6 class="mb-0 font-14">@blog.Blogid</h6>
                                                            </div>
                                                        </div>
                                                    </td>
                                                    <td>@blog.name</td>


                                                    <td>
                                                        <a href="/Blog/ChangeStatus?id=@blog.Blogid">
                                                            <i class="fas fa-edit"></i>
                                                                @(blog.HomeStatus == true ? "Enable" : "Disable")

                                                        </a>
                                                    </td>


                                                    <td class="align-middle">
                                                        <a href="/Blog/ViewDetail?id=@blog.Blogid" class="btn btn-primary btn-sm radius-30 px-4">View Detail</a>
                                                        <a href="/Blog/Update?id=@blog.Blogid" class="btn btn-info btn-sm radius-30 px-4">Update</a>
                                                        <a href="/Blog/Delete?id=@blog.Blogid" onclick="check(event)" class="btn btn-danger btn-sm radius-30 px-4">Delete</a>
                                                    </td>
                                                </tr>
                                                </form>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            }
                            else
                            {
                                <p>No blogs found.</p>
                            }
                        </div>
                    </div>
                </div>
            </div>
        }

        <script>
            function SearchByname() {

                $.ajax({
                    type: "GET",
                    url: '@Url.Action("searchBlogByName","Blog")',
                    data: { name: $('#searchBlog').val() },
                    success: function (result) {
                        // Handle the search results
                        $("#_blogList").empty();
                        $("#_blogList").html(result);
                    }
                });
            }
        </script>

    </main>
    <!-- end pageheader  -->
</div>

ProjectS/Views/Blog/searchBlogByName.cshtml
@model List<Blog>

@{
	Layout = null;
}

@if (Model == null)
{
	<p>No Blog found.</p>
}
else
{
	<div class="table-responsive">
        <table class="table mb-0">
            <thead class="table-light">
                <tr>
                    <th>Blog ID</th>
                    <th>Name</th>
                    <th>HomeStatus</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var blog in Model)
                {
                    <form method="post" asp-controller="Blog" asp-action="">
                        <input type="hidden" name="billId" value="@blog.Blogid" />

                    <tr>
                        <td>
                            <div class="d-flex align-items-center">

                                <div class="ms-2">
                                    <h6 class="mb-0 font-14">@blog.Blogid</h6>
                                </div>
                            </div>
                        </td>
                        <td>@blog.name</td>


                        <td>
                            <a href="/Blog/ChangeStatus?id=@blog.Blogid">
                                <i class="fas fa-edit"></i>
                                    @(blog.HomeStatus == true ? "Enable" : "Disable")

                            </a>
                        </td>


                        <td class="align-middle">
                            <a href="/Blog/ViewDetail?id=@blog.Blogid" class="btn btn-primary btn-sm radius-30 px-4">viewDetail</a>
                            <a href="/Blog/Update?id=@blog.Blogid" class="btn btn-info btn-sm radius-30 px-4">update</a>
                            <a href="/Blog/Delete?id=@blog.Blogid" onclick="check(event)" class="btn btn-danger btn-sm radius-30 px-4">Delete</a>
                        </td>
                    </tr>
                    </form>

                }

            </tbody>
        </table>
    </div>
}